### ISSUE TITLE
Character Encoding gives python error

### ISSUE THREAD

**Issue by ajvpot** [heapoutofspace/MVHP#3]
```
self.kick(u"%s§%s§%s" % (config.motd,
SyntaxError: (unicode error) 'utf8' codec can't decode byte 0xa7 in position 0: invalid start byte
```

Maybe escape the section symbols? I don't know much about python, but I'm trying to get this to work.

**Comment by heapoutofspace** [comment]
It's hard for me to fix this without being able to reproduce it. What happens when you replace all the `§`s with `\xa7`?

**Comment by ajvpot** [comment]
error: uncaptured python exception, closing channel <**main**.ClientTunnel connected '70.39.101.164:36062' at 0xb745b20c> (<type 'exceptions.UnicodeEncodeError'>:'ascii' codec can't encode character u'\xa7' in position 55: ordinal not in range(128) [/usr/lib/python2.6/asyncore.py|read|78] [/usr/lib/python2.6/asyncore.py|handle_read_event|428] [/usr/lib/python2.6/asynchat.py|handle_read|127] [proxy.py|collect_incoming_data|174] [proxy.py|kick|200] [proxy.py|log|153])

Edit: I've been messing with the code a bit, the line numbers are off. The issue is in an area I didn't touch though.

**Comment by heapoutofspace** [comment]
What version of python and what OS are you using?

**Comment by ajvpot** [comment]
Ubuntu 10.10 w/ Python 2.6.6

**Comment by heapoutofspace** [comment]
When using `\xa7`, did the exception occur before or after logging the kicking reason?

``` python
self.log("Kicking (%s)" % reason)
```

If it was after, what exactly was logged?

**Comment by ajvpot** [comment]
It seems that commenting out the logging of the kick fixed the issue.
That's where the exception occurred.

**Comment by heapoutofspace** [comment]
``` python
self.log(u"Kicking (%s)" % reason)
```

might fix it too.
